backend = "glx";
vsync = true;

shadow = true;            # ativa sombra
shadow-radius = 3;        # tamanho / blur da sombra
shadow-opacity = 0.18;    # intensidade (0.0 a 1.0)
shadow-offset-x = -3;     # distância horizontal
shadow-offset-y = -3;     # distância vertical

fading = true;
fade-delta = 10;

fade-in-step = 0.10;
fade-out-step = 0.10;

opacity-rule = [
  "90:class_g = 'kitty'"
]
